import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — venfii",
  description: "How venfii and the stores hosted on it handle your information.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-cream">
      <div className="mx-auto w-full max-w-3xl px-5 py-16 sm:px-8 sm:py-20">
        <Link href="/" className="text-sm font-semibold text-pine hover:underline">
          ← Back to venfii
        </Link>
        <h1 className="mt-6 font-heading text-4xl font-semibold text-charcoal">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-muted">
          Last updated: September 2026
        </p>

        <div className="mt-10 space-y-8 text-base leading-relaxed text-charcoal-soft">
          <Section title="1. What we collect">
            <p>When you open a venfii account, we collect:</p>
            <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm">
              <li>Your name, email address and phone number</li>
              <li>Your shop name, business category and store settings</li>
              <li>Payout details you provide (e.g. a Paystack account or bank details)</li>
              <li>Order and customer data generated by your store</li>
            </ul>
            <p className="mt-2">
              Visitors to stores hosted on venfii give us their name, contact
              details and order information when they place an order.
            </p>
          </Section>

          <Section title="2. How we use information">
            <ul className="list-disc space-y-1.5 pl-5 text-sm">
              <li>To run your store, process orders and send notifications</li>
              <li>To pass payment data to Paystack so orders can be paid and settled</li>
              <li>To provide support and communicate about your account</li>
              <li>To keep the Platform secure and detect fraud or abuse</li>
            </ul>
          </Section>

          <Section title="3. Payments">
            <p>
              Payments are processed by Paystack. We never store full card
              numbers. When you pay or connect a payout account, Paystack handles
              that data under its own terms and privacy policy; you should review
              them. Mobile money transactions are recorded by your network as
              normal.
            </p>
          </Section>

          <Section title="4. Sharing">
            <p>
              We do not sell your information. We share it only with service
              providers who help run the Platform (such as Paystack and email
              providers), when the law requires it, or with your permission. Data
              held for a store on venfii belongs to that store&apos;s owner, and
              sellers can export and delete it from their dashboard.
            </p>
          </Section>

          <Section title="5. Cookies &amp; analytics">
            <p>
              We use small cookies to keep you signed in and to remember simple
              preferences (for example, whether you have seen a promo screen).
              We also use error-tracking tooling (Sentry) to diagnose problems;
              it may collect technical details like browser type and error logs.
            </p>
          </Section>

          <Section title="6. How long we keep data">
            <p>
              We keep account and order records while your account is active and
              for a reasonable period afterwards to meet legal, tax and dispute
              obligations. You can request deletion at any time and we will
              remove or anonymise data we no longer need.
            </p>
          </Section>

          <Section title="7. Your rights">
            <p>
              You can access and update your information from your dashboard.
              To request a copy, correction or deletion, or to complain about the
              handling of your data, contact{" "}
              <a
                href="mailto:support@venfii.com"
                className="font-medium text-pine hover:underline"
              >
                support@venfii.com
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="flex items-center gap-3 font-heading text-lg font-semibold text-charcoal">
        {title}
      </h2>
      <div className="mt-2 text-sm leading-relaxed text-charcoal-soft sm:text-base">
        {children}
      </div>
    </section>
  );
}